config/routes.rb
Rails.application.routes.draw do
  resources :post_comments
  get 'pages/about'

  get 'pages/contact'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'categories/index'

  get 'categories/edit'

  get 'categories/new'

  get 'categories/show'

  get 'home/index'
  resources :posts
  resources :categories

  get '/about', :to => 'pages#about'
  get '/contact', :to => 'pages#contact'
  
  get '/categories/admin', to: redirect('/admin')
  get '/posts/admin', to: redirect('/admin')


    root 'home#index'








end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
		
end

app/models/category.rb
class Category < ActiveRecord::Base


	has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :category
	belongs_to :admin_user
	has_many :post_comment, :dependent => :destroy
end

app/models/post_comment.rb
class PostComment < ActiveRecord::Base
  belongs_to :post
  
  validates_presence_of :name
  validates_presence_of :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :all_categories
  helper_method :all_posts
  
  before_filter :site_search
  def site_search
  @q= Post.ransack(params[:q])
  @q_posts=@q.result(distinct: true)
  end
  
  def all_categories
  @categories = Category.all
  end
  
  def all_posts
  @posts = Post.all
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
		@categories = Category.all
	end
	
	def show
		@category = Category.find(params[:id])
		@title = @category.name
		@posts = @category.posts
	end

  def edit
  end

  def new
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  @posts = Post.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < InheritedResources::Base
def create
@post_comment = PostComment.new(post_comment_params)
	if @post_comment.save
		;flash[:notice] = "Comment was successfully created"
		redirect_to(@post_comment.post)
	else
		;flash[:notice] = "Error creating post comment"
		redirect_to(@post_comment.post)
	end
end

  private

    def post_comment_params
      params.require(:post_comment).permit(:name, :email, :body, :post_id)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
	@q = Post.ransack(params[:q])
	@posts=@q.result(distinct: true)
	end
	
	def show
		@post = Post.find(params[:id])
		@post_comment = PostComment.new(:post => @post)
	end
	
	def new
		@post = Post.new
		@category = Category.all
	end
	
	def create
	@post = Post.new(post_params)
		if @post.save
			redirect_to posts_path, :notice =>"Your post has been saved"
		else
			render "new"
		end
	end
	
	def edit
		@post = Post.find(params[:id])
	end
	
	def update
	@post = Post.find(params[:id])
		if @post.update_attributes(post_params)
			redirect_to post_path, :notice =>"Your post has been updated"
		else
			render "edit"
		end
	end
	
	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path, :notice=>"Your post has been deleted"
	end
	
		private
	def post_params
		params.require(:post).permit(:title, :body, :category_id, :admin_user_id)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<h2>List of categories</h2>
<hr>
<% @categories.each do |category| %>
	<%=link_to category.name,category%>
	<hr>
<% end%>

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

app/views/categories/show.html.erb
<% if @posts.each do |post| %>
<div class="article">
	<div class="clr"></div>
<h2><%= link_to post.title,post%></h2>
<img src="http://img.youtube.com/vi/<%=post.media %>/hqdefault.jpg" width="263" height="146" alt="" class="fl" />
<p><%= post.body %></p>
	 	 <p class="spec"><%= link_to "Read more", post, class: "rm" %></p>
</div>
<% end.empty? %>
<p>Sorry, there are no posts in this category</p>
<% end %>
<%= link_to "Back to categories", categories_path %>

app/views/home/index.html.erb
<% @posts.each do |post| %>
<div class="article">
	<div class="clr"></div>
	
	<h2><span><%=link_to post.title,post%></span></h2>
	<img src="http://img.youtube.com/vi/<%=post.media %>/hqdefault.jpg" width="263" height="146" alt="" class="fl" />
	<p><%=post.body%></p>
	 	 <p class="spec"><%= link_to "Read more", post, class: "rm" %></p>
</div>
<% end%>

app/views/layouts/application.html.erb
<%= render "partials/header" %>
  <div class="hbg">
    <div class="logo">
      <h1><a href="index.html"></a></h1>
    </div>
  </div>
  <div class="content">
    <div class="content_resize">
      <div class="mainbar">
	    <div class ="flashmessage">
		<% flash.each do |key,value|%>
		<p><%= value %></p>
		<%end%>
		</div>


	    <%= yield %>      
      </div>
<%= render "partials/sidebar" %>
      <div class="clr"></div>
    </div>
  </div>
  <%= render "partials/footer" %>

app/views/pages/about.html.erb
<h1>À propos</h1>
<p>YC movies est une association à but non lucratif domiciliée dans le canton de Neuchâtel. Son but premier est de permettre à de jeunes réalisateurs de créer des court-métrages artistiques de qualité.

Afin de financer les coûts de l'association, YC movies réalise régulièrement des projets promotionnels, des vidéos de mariage ou des vidéos de sports ou passions.

L'équipe de YC movies n'est pas constitué de professionnels. Chaque projet est pour nous une expérience de plus qui nous permet de nous améliorer. Toutefois, nous réalisons notre travail avec rigueur et nous respectons nos engagements.

Si vous avez besoin d'une vidéo promotionnelle ou si vous souhaitez voir nos court-métrages artistiques, contactez-nous. Nous nous ferons un plaisir de vous répondre.</p>

app/views/partials/_footer.html.erb
  <div class="fbg">
    <div class="fbg_resize">
      <div class="col c1">
        <h2><span>Image Gallery</span></h2>
        <a href="#"><img src="<%= asset_path('images/pix1.jpg') %>" width="56" height="56" alt="" /></a> <a href="#"><img src="<%= asset_path('images/pix2.jpg') %>" width="56" height="56" alt="" /></a> <a href="#"><img src="<%= asset_path('images/pix3.jpg') %>" width="56" height="56" alt="" /></a> <a href="#"><img src="<%= asset_path('images/pix4.jpg') %>" width="56" height="56" alt="" /></a> <a href="#"><img src="<%= asset_path('images/pix5.jpg') %>" width="56" height="56" alt="" /></a> <a href="#"><img src="<%= asset_path('images/pix6.jpg') %>" width="56" height="56" alt="" /></a> </div>
      <div class="col c2">
        <h2><span>Lorem Ipsum</span></h2>
        <p>Lorem ipsum dolor<br />
          Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec libero. Suspendisse bibendum. Cras id urna. <a href="#">Morbi tincidunt, orci ac convallis aliquam</a>, lectus turpis varius lorem, eu posuere nunc justo tempus leo. Donec mattis, purus nec placerat bibendum, dui pede condimentum odio, ac blandit ante orci ut diam.</p>
      </div>
      <div class="col c3">
        <h2><span>About</span></h2>
        <img src="<%= asset_path('images/white.jpg') %>" width="56" height="56" alt="" />
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec libero. Suspendisse bibendum. Cras id urna. Morbi tincidunt, orci ac convallis aliquam, lectus turpis varius lorem, eu posuere nunc justo tempus leo. llorem, eu posuere nunc justo tempus leo. Donec mattis, purus nec placerat bibendum. <a href="#">Learn more...</a></p>
      </div>
      <div class="clr"></div>
    </div>
  </div>
  <div class="footer">
    <div class="footer_resize">
      <p class="lf">Copyright &copy; 2010 <a href="#">SiteName</a> - All Rights Reserved</p>
      <p class="rf"><a href="http://all-free-download.com/free-website-templates/">Free CSS Templates</a> by <a href="http://www.iwebsitetemplate.com/">I Website Template</a></p>
      <div class="clr"></div>
    </div>
  </div>
</div>
<!-- END PAGE SOURCE -->
<div align=center>This template  downloaded form <a href='http://all-free-download.com/free-website-templates/'>free website templates</a></div>

</body>
</html>

app/views/partials/_header.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
  <title>ProjectYcmovies</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<!-- START PAGE SOURCE -->
<div class="main">
  <div class="header">
    <div class="header_resize">
      <div class="menu_nav">
	<ul >
	<li><%=link_to "Home", root_path %></li>
	<li><%=link_to "About", about_path %></li>
	<li><%=link_to "Contact", contact_path %></li>
	<li><%=link_to "Admin", "admin" %></li>
	</ul>
      </div>
      <div class="clr"></div>
    </div>
  </div>

app/views/partials/_post_comment.html.erb
<div class="post_comment">
<i><%=h post_comment.name %> says: </i><br />
<%= simple_format h(post_comment.body) %>
</div>

app/views/partials/_sidebar.html.erb
      <div class="sidebar">
        <div class="gadget">
		<h2 class="star"><span>Search</span></h2>
		  <ul class="sb_menu">
			<%= search_form_for @q do |f| %>
			<%= f.text_field :title_or_body_cont %>
			<%= f.submit "Search" %>
			<% end %>
          <h2 class="star"><span>Category</span></h2>
          <div class="clr"></div>
          <ul class="sb_menu">
		  <% all_categories.each do |cat| %>
		  <li><%= link_to cat.name,cat %></li>
		  <% end %>
          </ul>
          </ul>
        </div>
		
        <div class="gadget">
          <h2 class="star"><span>Posts</span></h2>
          <div class="clr"></div>
          <ul class="ex_menu">
		  <% all_posts.each do |post| %>
		  <li><%= link_to post.title,post %></li>
		  <% end %>
          </ul>
        </div>
      </div>

app/views/post_comments/_form.html.erb
<%= form_for(@post_comment) do |f| %>
  <% if @post_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post_comment.errors.count, "error") %> prohibited this post_comment from being saved:</h2>

      <ul>
      <% @post_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.text_field :post_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/post_comments/edit.html.erb
<h1>Editing Post Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @post_comment %> |
<%= link_to 'Back', post_comments_path %>

app/views/post_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Post Comments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Body</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post_comments.each do |post_comment| %>
      <tr>
        <td><%= post_comment.name %></td>
        <td><%= post_comment.email %></td>
        <td><%= post_comment.body %></td>
        <td><%= post_comment.post %></td>
        <td><%= link_to 'Show', post_comment %></td>
        <td><%= link_to 'Edit', edit_post_comment_path(post_comment) %></td>
        <td><%= link_to 'Destroy', post_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post comment', new_post_comment_path %>

app/views/post_comments/new.html.erb
<h1>New Post Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', post_comments_path %>

app/views/post_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post_comment.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @post_comment.email %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post_comment.body %>
</p>

<p>
  <strong>Post:</strong>
  <%= @post_comment.post %>
</p>

<%= link_to 'Edit', edit_post_comment_path(@post_comment) %> |
<%= link_to 'Back', post_comments_path %>

app/views/posts/edit.html.erb
<h1>edit new post</h1>
<%= form_for @post do |f| %>
	<p>
	<%= f.label :title%> <br />
	<%= f.text_field :title%> </br />
	</p>
	
		<p>
	<%= f.label :body%> <br />
	<%= f.text_area :body%> </br />
	</p>
	
	<p>
	<%= f.select :category_id, Category.all.collect {|x| [x.name,x.id]},{:include_blank=>"select one"}%> <br />
	</p>
	
	<p>
	<%= f.submit "Edit post"%> <br />
	</p>	
<%end%>
<%=link_to "Go back", post_path%>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<div class="article">
	<div class="clr"></div>
	
	<h2><span><%=link_to post.title,post%></span></h2>
	<img src="http://img.youtube.com/vi/<%=post.media %>/hqdefault.jpg" width="263" height="146" alt="" class="fl" />
	<p><%=post.body%></p>
	 <p class="spec"><%= link_to "Read more", post, class: "rm" %></p>
</div>
<% end%>

app/views/posts/new.html.erb
<h1>add new post</h1>
<%= form_for @post do |f| %>
	<p>
	<%= f.label :title%> <br />
	<%= f.text_field :title%> </br />
	</p>
	
		<p>
	<%= f.label :body%> <br />
	<%= f.text_area :body%> </br />
	</p>
	
	<p>
	<%= f.select :category_id, Category.all.collect {|x| [x.name,x.id]}%> <br />
	</p>
	
	<p>
	<%= f.submit "add post"%> <br />
	</p>
	

<%end%>

app/views/posts/posts/edit.html.erb
<h1>edit post</h1>
<%= form_for @post do |f| %>
	<p>
	<%= f.label :title%> <br />
	<%= f.text_field :title%> </br />
	</p>
	
		<p>
	<%= f.label :body%> <br />
	<%= f.text_area :body%> </br />
	</p>
	
	<p>
	<%= f.select :category_id, Category.all.collect {|x| [x.name,x.id]},{:include_blank=>"select one"}%> <br />
	</p>
	
	<p>
	<%= f.submit "update post"%> <br />
	</p>
<%end%>
<%= link_to "Go back", post_path %>

app/views/posts/posts/index.html.erb
<h1>Blog post</h1>
<% @posts.each do |post| %>
	<h1><%=link_to post.title,post%></h1>
	<p><%=post.body%></p>
	<hr>
<% end%>
<%= link_to "Add new Post", new_post_path%>

app/views/posts/posts/new.html.erb
<h1>add new post</h1>
<%= form_for @post do |f| %>
	<p>
	<%= f.label :title%> <br />
	<%= f.text_field :title%> </br />
	</p>
	
		<p>
	<%= f.label :body%> <br />
	<%= f.text_area :body%> </br />
	</p>
	
	<p>
	<%= f.select :category_id, Category.all.collect {|x| [x.name,x.id]},{:include_blank=>"select one"}%> <br />
	</p>
	
	<p>
	<%= f.submit "add post"%> <br />
	</p>
	

<%end%>

app/views/posts/posts/show.html.erb
<h1><%=@post.title%></h1>
<small><%=@post.created_at.strftime("%m.%d.%Y")%></small>
<p><%=@post.body%></p>
<p><%=@post.category.name%></p>
<%=link_to "Edit Post", edit_post_path%> | <%= link_to "Delete", @post, data:{:confirm => "Are you sure you want to delete?"}, :method=>:delete%>

app/views/posts/show.html.erb
<h1><%=@post.title%></h1>
<small>posted : <%=@post.created_at.strftime("%m %b %Y")%></small>
<p>Created by : <%=@post.admin_user.name%></p>
<p><%=@post.body%></p>
 <iframe width="420" height="315"
src="https://www.youtube.com/embed/<%= @post.media %>"frameborder = "0" allowfullscreen >
</iframe> 
<p>Category : <%=@post.category.name%></p>

<%= form_for @post_comment do |f| %>
<%= f.hidden_field :post_id %>
<p>
<%= f.label :name %><br />
<%= f.text_field :name %>
</p>

<p>
<%= f.label :email %><br />
<%= f.text_field :email %>
</p>

<p>
<%= f.label :body %><br />
<%= f.text_area :body %>
</p>

<p>
<%= f.submit "Post comment" %>
</p>
<%end%>
<%= render :partial => 'partials/post_comment', :collection => @post.post_comment %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>